---
title: "資料分析實戰"
author: "Yao-Jen Kuo"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 簡介

在這份報告裡面我下載 [Kaggle](https://www.kaggle.com/) 的 Titanic 訓練與測試來進行資料整理，探索性分析與機器學習的分類模型。

## 資料讀取

我使用 `read.csv()` 函數讀入資料集。

```{r}
titanic_train <- read.csv("https://storage.googleapis.com/r_rookies/kaggle_titanic_train.csv", stringsAsFactors = FALSE)
```

## 資料框外觀

我使用 `str()` 函數得知這個資料有 891 個觀測值與 12 個變數。

```{r}
str(titanic_train)
```

## 描述性統計與資料清理

我使用 `summary()` 函數進行描述性統計。

```{r}
summary(titanic_train)
```

我發現這個資料的 `Age` 變數有 177 個遺漏值，我決定用中位數填補這些遺漏值。

```{r}
age_median <- median(titanic_train$Age, na.rm = TRUE)
titanic_train$Age[is.na(titanic_train$Age)] <- age_median
summary(titanic_train$Age)
```

## 探索性分析

我利用 `ggplot2` 與 `plotly` 套件來作圖。

```{r message = FALSE}
library(ggplot2)
library(plotly)
```

```{r}
# 性別
ggplot_bar_sex <- ggplot(titanic_train, aes(x = Sex, y = Survived, fill = Sex)) + geom_bar(stat = "identity")
ggplot_bar_sex_plotly <- ggplotly(ggplot_bar_sex)
ggplot_bar_sex_plotly

# Pclass
ggplot_bar_pclass <- ggplot(titanic_train, aes(x = factor(Pclass), y = Survived, fill = factor(Pclass))) + geom_bar(stat = "identity", width = .7)
ggplot_bar_pclass_plotly <- ggplotly(ggplot_bar_pclass)
ggplot_bar_pclass_plotly
```

## 建立一個分類模型

### 決策樹

我利用 `rpart()` 函數建立一個決策樹分類模型來預測 `Survived` 變數。

```{r}
# 切分訓練與測試資料
set.seed(123)
n <- nrow(titanic_train)
shuffled_titanic <- titanic_train[sample(n), ]
train_indices <- 1:round(0.7 * n)
train_titanic <- shuffled_titanic[train_indices, ]
test_indices <- (round(0.7 * n) + 1):n
test_titanic <- shuffled_titanic[test_indices, ]

# 建立分類器
library(rpart)
titanic_clf <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Embarked, data = train_titanic, method = "class")

# 預測
test_titanic_predicted <- predict(titanic_clf, test_titanic, type = "class")

# 績效
conf_mat <- table(test_titanic$Survived, test_titanic_predicted)
accuracy <- sum(diag(conf_mat)) / sum(conf_mat)
accuracy

# 上傳資料
url <- "https://storage.googleapis.com/py_ds_basic/kaggle_titanic_test.csv"
to_predict <- read.csv(url, stringsAsFactors = FALSE)
predicted <- predict(titanic_clf, to_predict, type = "class")
to_submit <- data.frame(to_predict[, "PassengerId"], predicted)
head(to_submit, n = 20)
# write.csv(to_submit, file = "to_submit.csv")
```