---
title: "單一變數與函數 - 隨堂練習"
author: "Yao-Jen Kuo"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: false
---

```{r, include=FALSE}
tutorial::go_interactive()
```

## 換算公里與英里

Tony 是長跑的愛好者，他常常在美國的跑步論壇搜尋訓練相關資訊，但是這些資訊都是用英里（mile）計算，他不知道全程馬拉松 42.195 公里換算成英里是多少？讓我們用 R 語言的命令列當作計算機來幫助他吧！

```{r ex="km_mile_converter", type="sample-code"}
# 1 km equals to 0.621371192 miles
km_to_mile <- 

# Print km_to_mile in the console


# The distance of full marathon measured in km
full_marathon_km <- 42.195

# The distance of full marathon measured in mile
full_marathon_mile <- 
  
# Print full_marathon_mile in the console

```

```{r ex="km_mile_converter", type="solution"}
# 1 km equals to 0.621371192 miles
km_to_mile <- 0.621371192

# Print km_to_mile in the console
km_to_mile

# The distance of full marathon measured in km
full_marathon_km <- 42.195

# The distance of full marathon measured in mile
full_marathon_mile <- full_marathon_km * km_to_mile
  
# Print full_marathon_mile in the console
full_marathon_mile
```

```{r ex="km_mile_converter", type="sct"}
test_object("km_to_mile", incorrect_msg = "Assign 0.621371192 to `km_to_mile`.")
test_object("full_marathon_mile", incorrect_msg = "Calculate `full_marathon_mile` by multiplying `full_marathon_km` with `km_to_mile`.")
test_output_contains("km_to_mile", incorrect_msg = "Make sure to print `km_to_mile`.")
test_output_contains("full_marathon_mile", incorrect_msg = "Make sure to print `full_marathon_mile`.")
success_msg("Thank you so much, now Tony knows that the distance of a full marathon course is 26.2 miles!")
```