---
title: "簡單的統計與繪圖 - 隨堂練習"
author: "Yao-Jen Kuo"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: false
---

```{r, include=FALSE}
tutorial::go_interactive()
```

## 計算一組隨機變數向量的統計量

```{r ex="stats_graph", type="sample-code"}
# Generate a vector with 10 random integers between 1 and 100
random_integers <- round(runif(10) * 100)

# Use quantile() to get the 5% and 95% quantile
qunatile(___, probs = c(___, ___))

# Use median() to get the median


# Use mean() to get the mean

```

```{r ex="stats_graph", type="solution"}
# Generate a vector with 10 random integers between 1 and 100
random_integers <- round(runif(10) * 100)

# Use quantile() to get the 5% and 95% quantile
quantile(random_integers, probs = c(0.05, 0.95))

# Use median() to get the median
median(random_integers)

# Use mean() to get the mean
mean(random_integers)
```

```{r ex="stats_graph", type="sct"}
test_output_contains("quantile(random_integers, probs = c(0.05, 0.95))", incorrect_msg="Did you use quantile() correctly?")
test_output_contains("median(random_integers)", incorrect_msg="Did you use median() correctly?")
test_output_contains("mean(random_integers)", incorrect_msg="Did you use mean() correctly?")
```